version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Express

  rabbit:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3.6.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
        
  seq:
    container_name: seq
    hostname: seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "8080:80"
      - "5341:5341"